### ISSUE TITLE
Add calendar extension for Brave Talk on Google Calendar

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#10]
This is a fork/branch of the [Jitsi calendar plugin](https://github.com/jitsi/jidesha) in order to add a Brave Talk confab URL to a calendar entry. The idea is to put the CRX file on Brave Talk so folks who use Google Calendar can add a confab URL to the calendar invite, e.g., 
![Screen Shot 2021-11-16 at 17 22 14](https://user-images.githubusercontent.com/400552/142075706-c8bbe834-f035-4061-bd00-f0cbd1eb61a9.png)
![Screen Shot 2021-11-16 at 17 22 40](https://user-images.githubusercontent.com/400552/142075717-48b1ea7c-9f56-49e1-8cab-76f5a015ccde.png)
(Note that the icons are still Jitsi icons. These will be updated to Brave Talk icons soon.)

**Comment by mrose17** [comment]
Now onto the design for phase 2: having the plugin "schedule" a room for subscribers, so they get moderator privileges!

**Comment by tackley** [comment]
# Creating the Room with Moderator Privileges
## Context
Making use of the mechanics implemented for the `/talk` slack plugin (i.e. passing the `create=y` query parameter), it is possible for this chrome extension to generate a room name which will get created on first use, without any communication with `talk.brave.com`. This is what @mrose17 described as "turns out this is fairly straight-forward".

However, that approach comes with a significant limitation: the _first subscriber_ to enter the room is the one who gains moderator privileges. We would obviously prefer the person who scheduled the call to have those privileges.

In order to achieve that, due to the unique privacy-focused model of talk:
1. the user's issued credentials need to be presented to the create room api call. These credentials are only present in `talk.brave.com`'s localStorage.
2. the resulting jwt and refresh token need to be stored in `talk.brave.com`'s localStorage.

## Investigation 1
Use message passing to initiate room creation within the context of `talk.brave.com`.

Extensions communicate between their (global) service worker and content scripts injected to specific pages using the `sendMessage` api as described [here]( https://developer.chrome.com/docs/extensions/mv3/messaging/).

However, on `talk.brave.com` we want to invoke the existing code within the page that creats a room. Standard web pages cannot participate in the extension-specific `sendMessage` api, so we need to inject a content script to `talk.brave.com` and convert those messages to `postMessage` calls, as described [here](https://developer.chrome.com/docs/extensions/mv3/content_scripts/#host-page-communication). This results in a setup like this:

![image](https://user-images.githubusercontent.com/51444/145199647-a7abc5ad-aef8-45fb-8bc2-95d142293e82.png)
[[diagram link](https://mermaid.live/edit/#eyJjb2RlIjoic2VxdWVuY2VEaWFncmFtXG5hdXRvbnVtYmVyXG5wYXJ0aWNpcGFudCBDYWwgYXMgY2FsZW5kYXIuZ29vZ2xlLmNvbVxucGFydGljaXBhbnQgQ1NfY2FsIGFzIEV4dGVuc2lvbjogQ29udGVudCBTY3JpcHQgKEdDQUwpXG5wYXJ0aWNpcGFudCBTIGFzIEV4dGVuc2lvbjogU2VydmljZSBXb3JrZXIgXG5wYXJ0aWNpcGFudCBDU190YWxrIGFzIEV4dGVuc2lvbjogQ29udGVudCBTY3JpcHQgKFRhbGspXG5wYXJ0aWNpcGFudCBUYWxrIGFzIHRhbGsuYnJhdmUuY29tXG5cbkNTX2NhbC0-PkNhbDogaW5qZWN0IFwiQWRkIEJyYXZlIFRhbGtcIiBCdXR0b25cbk5vdGUgbGVmdCBvZiBDU19jYWw6IENsaWNrXG5DU19jYWwtPj5TOiBzZW5kTWVzc2FnZSBcImNyZWF0ZSByb29tXCJcbm5vdGUgcmlnaHQgb2YgUzogb3BlbiBuZXcgdGFiIGlmIG5vIHRhbGsgdGFiIG9wZW5cblMtPj5DU190YWxrOiBzZW5kTWVzc2FnZSBcImNyZWF0ZSByb29tXCJcbkNTX3RhbGstPj5UYWxrOiBwb3N0TWVzc2FnZSBcImNyZWF0ZSByb29tXCJcbm5vdGUgcmlnaHQgb2YgVGFsazogdXNlcyBjcmVkZW50aWFscyB0byBjcmVhdGUgcm9vbVxubm90ZSByaWdodCBvZiBUYWxrOiBzdG9yZXMgSldUXG5UYWxrLT4-Q1NfdGFsazogcG9zdE1lc3NhZ2UgXCJyb29tIGNyZWF0ZWRcIlxuQ1NfdGFsay0-PlM6IHJvb20gY3JlYXRlZFxubm90ZSByaWdodCBvZiBTOiBjbG9zZSB0YWxrIHRhYiBpZiBvcGVuZWRcblMtPj5DU19jYWw6IHJvb20gY3JlYXRlZFxuQ1NfY2FsLT4-Q2FsOiBwb3B1bGF0ZSBsb2NhdGlvbiB3aXRoIHRhbGsgdXJsIiwibWVybWFpZCI6IntcbiAgXCJ0aGVtZVwiOiBcImRlZmF1bHRcIlxufSIsInVwZGF0ZUVkaXRvciI6ZmFsc2UsImF1dG9TeW5jIjp0cnVlLCJ1cGRhdGVEaWFncmFtIjpmYWxzZX0)]


Most of this is pretty simple and I've successfully prototyped much of it. The mechanics between steps 4 and 5 are ugly and error prone as `postMessage` is totally asynchronous and unlike `sendMessage` cannot return a response, so the content script injected into `talk.brave.com` would need to cache callbacks in order to tie up with the request from step 3.

However, dealing with failure cases is even more complex, the most obvious being that the user is not logged in as a subscriber. We can only discover this between steps 4 and 5, at which point presenting a UI to the user to login is difficult, as the tab will be in the background.

**Comment by mrose17** [comment]
Here is the "final" product... thank you @tackley 

![Screen Shot 2022-02-14 at 14 45 50](https://user-images.githubusercontent.com/400552/153935314-839e5c88-786d-46af-be0a-452d766f3507.png)

**Comment by stephendonner** [comment]
Looks and works great for me from `talk.brave.software` using 

Brave | 1.36.90 Chromium: 98.0.4758.87 (Official Build) beta (64-bit)
-- | --
Revision | e4cd00f135fb4d8edc64c8aa6ecbe7cc79ebb3b2-refs/branch-heads/4758@{#1002}
OS | Windows 10 Version 21H2 (Build 19044.1526)

example | example | example | example | example
----------|-----------|----------|-----------|----------
![brave-talk-calendar-1](https://user-images.githubusercontent.com/387249/154005160-3cb45c13-0d16-424b-9fc0-e85a8f99a81a.png) | ![brave-talk-calendar-2](https://user-images.githubusercontent.com/387249/154005162-9c457dad-446a-46b7-aa58-ac96fbb9e62c.png) | ![brave-talk-calendar-3](https://user-images.githubusercontent.com/387249/154005165-0d1fdebf-febd-4ec1-a231-0780c2b14154.png) | ![brave-talk-calendar-4](https://user-images.githubusercontent.com/387249/154005166-9af65846-71a7-4651-af29-37bc6e9b93dd.png) | ![brave-talk-calendar-5](https://user-images.githubusercontent.com/387249/154005168-173ddaa4-7168-46b2-a35c-d0710199f1aa.png)

**Comment by mrose17** [comment]
Fixed by https://github.com/brave/brave-talk/pull/176

**Comment by stephendonner** [comment]
Filed https://github.com/brave/brave-talk/issues/180 on the Brave Talk icon-transparency issue in the Google Chrome Store.

**Comment by mrose17** [comment]
Closed by release of https://chrome.google.com/webstore/detail/brave-talk-for-google-cal/nimfmkdcckklbkhjjkmbjfcpaiifgamg
