### ISSUE TITLE
Question: Are the (same) meeting links reused?

### ISSUE THREAD

**Issue by ElsAr4e** [brave/brave-talk#1287]
If you generate a meeting link and after all peers end the call - Does Brave “remember” / do servers store the meeting link so that it will NEVER be used again by other persons?

Or can it happen that another person at another time generates the same meeting link (for example a week/ month / year late) again (randomly)?

**Comment by mrose17** [comment]
Meeting room paths are pseudo-randomly generated each time someone clicks on either "Start Premium call" or "Start free call". The path contains 256 bits of entropy, encoded for use in a URL, which is why the room path may look "odd".

When the last person leaves a room, all of the state (e.g., chat messages) are wiped. If the moderator didn't turn off recording, then recording also stops when the last person leaves. In other words, when the last person leaves, the system "sweeps the floor, empties the waste baskets, and turns off all the lights."

Accordingly, if someone goes back to the room after it became empty, then they are going to a brand-new room that just happens to have the same meeting room path as the earlier instance... but nothing gets inherited/copied/pasted from any earlier instance.

**Comment by ElsAr4e** [comment]
> When the last person leaves a room, all of the state (e.g., chat messages) are wiped.

So it could happen that another user might randomly generate the same link in the future?
(The link for example is not stored on any server that will reject the generation of the same link in the future and forces the servers to generate another one that has never ever been used before?)

But of course a new peer that (randomly) generates the (same) link for the first time won't be able to access any (deleted) data from a previous meeting?

**Comment by mrose17** [comment]
It is theoretically possible for collisions to occur; however we're talking about ~10^77 possibilities; regardless, it doesn't matter, as noted earlier, when the last person leaves, the state is wiped.

**Comment by ElsAr4e** [comment]
Thank you for the clarification and your answer!

Should this information be added to the website BraveTalk (for example FAQ)?
Because I think it would be useful.

**Comment by mrose17** [comment]
I will ask that the FAQ be updated!

**Comment by ElsAr4e** [comment]
Thanks!

**Comment by mrose17** [comment]
@ElsAr4e - cf., https://support.brave.com/hc/en-us/articles/4409911973261-How-do-I-use-Brave-Talk-#h_01HEXQ1SNBKGFB3RRXBSX6KFDZ

**Comment by ElsAr4e** [comment]
@mrose17 Maybe we can also mention that even statistics are not collected / stored (if my information is correct)?
(Example of statistics of a call: https://support.zoom.com/hc/en/article?id=zm_kb&sysparm_article=KB0070504#h_dd5a3ef9-4857-4aad-b445-4dc7d52f7dce)

Brave won't collect or store any data after all people left the meeting? Not even anonymous data? Every data of the meeting will be deleted irrevocably (making it technically impossible to recover any data from the meeting)?

If it should be technically impossible to recover any data from the meeting which methods does Brave use?
Examples:
https://seamservices.com/blog/why-overwriting-isnt-enough-to-erase-data/

Methods:
https://www.lifewire.com/data-sanitization-methods-2626133

**Comment by ElsAr4e** [comment]
@mrose17 One question: If all persons left how long does Brave Talk remember the moderator? Does Brave Talk remember the moderator because of the IP address of the moderator?

Or will Brave Talk don't know the moderator anymore as soon as all persons have left the meeting (if you are using the free version of Brave Talk (unregistered)?
And nobody will ever be moderator - unless the same link is randomly generated?
