### ISSUE TITLE
Add 'Create link' button to NTP widget

### ISSUE THREAD

**Issue by mattmcalister** [brave/brave-talk#78]
The Brave Talk NTP widget has a button to 'Start video call'. This is a very useful widget, and it will get a lot of exposure. Just as we have on the talk.brave.com home page the widget also needs an option to 'Create link' so that people can get the URL for a call and share it with people easily.

![Screenshot 2021-12-07 at 20 28 56](https://user-images.githubusercontent.com/71029/145101456-3916e5d0-376f-44ff-9517-7c39f0a40762.png)

![image](https://user-images.githubusercontent.com/71029/145101561-2b861061-d022-4a11-bdeb-d835cb66cc2e.png)

**Comment by mtmulch** [comment]
@mrose17 

I was using Brave pretty extensively and I'm a fan of TypeScript. I noticed this feature and came into the source. Based on the issue described you are asking for a the 'Create Link' to perform the same generation of a talk Brave link so that users can perform a copy and paste to other users that are being invited to the call.
