### ISSUE TITLE
Add "BAT gating"

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#943]
Instead of requiring ownership of an NFT in a collection, or membership in a POAP group, require at least X BAT.

cf., https://docs.google.com/document/d/193d9IQa33QfnxHnSW-lrv3PgjW2ztZXQuSqQW3nxVYU/edit#heading=h.tj5oevppm9ha

**Comment by srirambv** [comment]
The following checks are done on `https://talk.brave.software/`
- Create a BAT gated call with a wallet that has 0 BAT Balance - ✅ 
- Create a BAT gated call with a wallet that has BAT balance - ✅ 
- Create a BAT gated call with hardware wallet with BAT balance -  ✅ 
- Create a BAT gated call with hardware wallet with 0 BAT balance -  ✅ 
- Join a BAT gated call with a wallet that has BAT balance (irrespective of who created the call) -  ✅ 
- Join a BAT gated call with a wallet that has 0 BAT balance (irrespective of who created the call) - :x: (expected behaviour so  ✅)
- Join a BAT gated call from a wallet using extension -  ✅ 
- Join a BAT gated call from a 0 BAT balance wallet using extension - :x: (expected behaviour so  ✅)
- Join a BAT gated call from a hardware wallet with BAT balance -  ✅ 
- Join a BAT gated call from a hardware wallet with 0 BAT balance - :x: (expected behaviour so  ✅)

**Comment by mrose17** [comment]
@srirambv - may I interpret this as: ready for deploy?

**Comment by srirambv** [comment]
@mrose17 Yes ready for deploy
