### ISSUE TITLE
add SOL NFT gating

### ISSUE THREAD

**Issue by mrose17** [brave/brave-talk#944]
Use ownership of an NFT in a SOl-based NFT collection.

cf., https://docs.google.com/document/d/193d9IQa33QfnxHnSW-lrv3PgjW2ztZXQuSqQW3nxVYU/edit#heading=h.tj5oevppm9ha

**Comment by srirambv** [comment]
The following checks are done on `https://talk.bravesoftware.com`

* **Create a SOL gated call with no participant requirement from Brave** 
   * Join the call with no participant requirement from Brave - ✅ 
   * Join the call with no participant requirement from other browser using extension - ✅ 
   
* **Create a SOL gated call with participant NFT requirement** 
   * Join the call with participant NFT requirement using Brave wallet that has the required NFT - ✅ 
   * Join the call with participant NFT requirement in other browser using extension that has the required NFT - ✅ 
   * Join the call with participant NFT requirement from Brave/other browser using extension which **doesn't** have the required NFT - ❌ (expected behaviour so ✅)

* **Create a SOL gated call with moderator NFT requirement** 
   * Join the gated call with moderator NFT requirement using Brave wallet that has the required NFT - ✅ 
   * Join the call with moderator NFT requirement using other Browser with extension that has the required NFT - ✅ 
   * Join the call with moderator NFT requirement using Brave wallet that **doesn't** has the required NFT - ✅ 
   * Join the call with moderator NFT requirement using other Browser with extension that **doesn't** has the required NFT - ✅

* **Create a SOL gated call with participant and moderator NFT requirement** 
   * Join the call from Brave with only participant NFT - ✅ 
   * Join the call from Brave with only moderator NFT - ❌ (expected behaviour so✅)
   * Join the call from Brave without any NFT - ❌  (expected behaviour so ✅)
   * Join the call from other browser using extension with only participant NFT - ✅  
   * Join the call from other browser using extension with only moderator NFT - ❌ (expected behaviour so✅)
   * Join the call from other browser using extension without any NFT - ❌  (expected behaviour so ✅)

**Comment by mrose17** [comment]
Fixed by https://github.com/brave/brave-talk/pull/1206 ... thank you @hadiamjad !!!
